spring:
  config:
    import: aws.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: ${db.ddl}
    properties:
      hibernate:
        format_sql: ${hibernate.format_sql}
        highlight_sql: ${hibernate.highlight_sql}
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: com.dnd.ground.global.config.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    timeout: ${spring.redis.timeout}
  main:
    allow-bean-definition-overriding: true
logging:
  config: classpath:log4j2.xml
  level:
    org.hibernate.SQL: debug
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

# 외부 설정 정보
kakao:
  REST_KEY: ${kakao.REST_KEY}
  REDIRECT_URI: ${kakao.REDIRECT_URI}
apple:
  ISS: ${apple.ISS}
  AUD: ${apple.AUD}
fcm:
  project_id: ${fcm.project_id}
  key:
    path: ${fcm.key.path}
    scope: ${fcm.key.scope}

# 내부 설정 정보
ip: ${ip}
picture:
  path: ${picture.path}
  name: ${picture.name}
jwt:
  secret_key: ${jwt.secret_key}
  issuer: ${jwt.issuer}